### ISSUE TITLE
User and password from configuration

### ISSUE THREAD

**Issue by pdincau** [rbishop/plug_basic_auth#11]
Would it be possible to extract user and password from configuration?

**Comment by rbishop** [comment]
You could do that by putting the configuration in your application:

```elixir
config :my_app, 
  :basic_auth_user: "Foo",
  :basic_auth_password: "Bar"
```

and then using that where you plug `PlugBasicAuth`:

```elixir
defmodule MyApp.Controller
...
plug PlugBasicAuth,
        username: Application.get_env(:my_app, :basic_auth_user),
        password: Application.get_env(:my_app, :basic_auth_password)
...
end
```

Or are you suggesting we make PlugBasicAuth a configurable OTP application so you could do something like:

```elixir
config :plug_basic_auth, username: "Foo", password: "Bar"
```

**Comment by pdincau** [comment]
the first solution works fine for me. Sorry, looking at it I can say it was very easy ;D
thanks
