### ISSUE TITLE
Proposal: Add callback to determine whether the authentication is successful or not

### ISSUE THREAD

**Issue by amilkr** [rbishop/plug_basic_auth#12]
Hi guys, 
A couple of weeks ago I needed a plug to add basic auth.
In my case, to determine if the authentication is successful I have to check the database. So that, I ended up forking this repo and updating it to be able to add a callback function which is going to be called by the plug to validate the auth. 
[This commit](https://github.com/amilkr/plug_basic_auth/commit/e3496394de1b211c6f3312eac66f95de274b6ea3) has my changes. 

What do you think about it? Would you consider to add this callback? 
I could create a PR from my branch. I deleted the `:username` and `:password` keys and their implementation. I could update my code to support both strategies: validation callback and username/password.

Thanks

**Comment by rbishop** [comment]
Sorry for the delay in getting back tot his. This is the second or third time I'm getting this request so I would be open to it. If you have some code to share please do! This is alsoi similar to what #13 is asking for and we can accomplish both at the same time.

**Comment by amilkr** [comment]
@rbishop I created the PR with my changes. Let me know what you think. Thanks
