### ISSUE TITLE
Allow runtime setting of credentials

### ISSUE THREAD

**Issue by srid** [rbishop/plug_basic_auth#13]
For example, from system environment variables. This doesn't seem possible in the current state of plug_basic_auth. The other plug actually supports it: https://github.com/bitgamma/plug_auth#http-basic-example

**Comment by rbishop** [comment]
This is similar to #12. Let's see if we can accommodate both at the same time. Be warned I'm quite busy these days and it might be several weeks before I can whip this up but I'm happy to review any code you wish to contribute.

**Comment by srid** [comment]
This was added as part of https://github.com/amilkr/plug_basic_auth/pull/3
